### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#237]
Front page should have a leaderboard with top 3-5 users all time and this month.

**Comment by almasaeed2010** [comment]
Before implementing this, let's define what categorizes best user.
- Number of observations
Is there anything else?

For the top user this month version, I think this should be the most recent observations within 30 days period instead of a specific month or the last 30 days since we can have 30 days with no submissions at all.

**Comment by bradfordcondon** [comment]
nope.  Are you thinking general avatars or for leaderboard winners or something?

**Comment by almasaeed2010** [comment]
yeah like crowns or whatever

**Comment by almasaeed2010** [comment]
Implemented.

- [ ] Push live
