### ISSUE TITLE
feature request: user tools

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#279]
ellen has requested some better user sorting and reporting features.

Some questions she has:

What users joined this month?
Who are the top users this month/all time?
I think giving the admin area when browsing users some sorting/filtering would help her.

**Comment by almasaeed2010** [comment]
Yeah I actually started working on this. The users over time chart will have an expand button that shows a full report of which users joined which month. You'll also be able to choose a date range to view statistics for.

It'd be nice to have all of the suggestions/questions that we want listed though so that I don't go overboard (as I sometimes do lol)

**Comment by bradfordcondon** [comment]
i emailed ellen for clarification

**Comment by almasaeed2010** [comment]
@ellen Finally got to this and published it live. For the time being, the download button will simply create a CSV file that has all the info you requested. To try it:

1. Go to https://treesnap.org/admin/users
1. Click Download

It may be a little slow since you are downloading the entire list of users. We can speed it up by adding filters such as users registered after a given date. Would you be interested in that kind of functionality (filtering)?

Thanks!
