### ISSUE TITLE
Group members share by default

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-website#334]
Privacy options are a bit complicated when opting to join a group. Suggestions:
- group members (but not leader) always automatically share all their observations with the group
- default is for group members (but not leader) to share all their observations with the group, but a way to turn this off is also provided

**Comment by almasaeed2010** [comment]
Turns out the default is already set to allow sharing for non-leaders. 

Making changes to permissions to allow the leader to automatically get all the observations is going to take some time to implement since that means tweaking all the places where we check for permissions (map, downloads, filters, collections, etc).

Maybe it's time to come up with a more sophisticated permissions system where everything is controlled using a permissions controller/class. That way a change in one place can affect all parts of the code.

**Comment by almasaeed2010** [comment]
So it turns out we had a bug in the sharing script where no matter what the user chose when accepting the invite, it's auto set to not to share. I submitted a fix for it in #345. I think will clear some confusion.
