### ISSUE TITLE
ensure Florida shows up on the TreeSnap map

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-website#336]

**Comment by almasaeed2010** [comment]
I am not sure how we are supposed to do this lol

The map centers itself based on the size of your window to show as much of the US as possible whilst not zooming out too much. The zoom is tuned to speedup the loading the of map by not overloading the view with too many observations so changing it at this point will require implementing #342. There isn't really a way to predict which states will show up unless we specifically center the map around Florida instead of the US.

**Comment by bradfordcondon** [comment]
i have a solution!  The map centers around the average center of your observations.

**Comment by almasaeed2010** [comment]
Interesting and we do that on the phone but it's not as easy on the site map since you don't just have your observations there so you can't use the google api to find the center and pan to it.
